### ISSUE TITLE
LinkedIn Events

### ISSUE THREAD

**Issue by cheeaun** [PicoCreator/list-of-meetup-alternatives#5]
Seems new, not sure if can be useful.

News: https://techcrunch.com/2019/10/15/linkedin-gets-physical-debuts-new-events-hub-for-people-to-plan-in-person-networking-events/

I personally haven't tried it, also don't know if anyone else tried it.

**Comment by PicoCreator** [comment]
Wow - while it was on trial since last year (which is good, since it means time to iron out bugs)

I wonder did they fast forward their official launch because of meetup.com

**Comment by PicoCreator** [comment]
Anyway added it in

https://github.com/PicoCreator/list-of-meetup-alternatives/commit/9f344f200a0a9bbfafe66d9daddcbe9e7f521fcc

Thanks for the info =)
